### ISSUE TITLE
PRACTICA #6 HILOS EN UNA CONSOLA DE UN CAJERO 

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/practica-de-hilos-magaly1311#2]
[Hilos.zip](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-magaly1311/files/8460363/Hilos.zip)

**Comment by magaly1311** [comment]
[PRACTICA #6HILO MAGALY NICOLAS SACNHEZ .pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-magaly1311/files/8566485/PRACTICA.6HILO.MAGALY.NICOLAS.SACNHEZ.pdf)
PRACTICA #6

**Comment by EvelynLopezz** [comment]
Calificación de la practica Magaly Nicolas Sánchez:
19.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
